blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from blog import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^$', views.post_list, name='post_list'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'
        r'(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    url(r'^search/$', views.post_search, name='post_search')
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    objects = models.Manager()
    published = PublishedManager()
    STATUS_CHOICES = {
        ('draft', 'Draft'),
        ('published', 'Published')
    }
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish', )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)
    

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from haystack.query import SearchQuerySet


def post_search(request):
    form = SearchForm()
    cd = None
    results = None
    total_results = None
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            cd = form.cleaned_data
            results = SearchQuerySet().models(Post).filter(content=cd['query']).load_all()
            total_results = results.count()
    return render(request, 'post/search.html', {'form': form,
                                                'cd': cd,
                                                'results': results,
                                                'total_results': total_results})


# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'post/list.html'


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'post/list.html', {'page': page,
                                              'posts': posts,
                                              'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')) \
                        .order_by('-same_tags', '-publish')[:4]

    return render(request, 'post/detail.html', {'post': post,
                                                'comments': comments,
                                                'comment_form': comment_form,
                                                'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = '{} ({}) recommends you reading "{}"'. \
                format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\' comments: {}'. \
                format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'post/share.html', {'post': post,
                                               'form': form,
                                               'sent': sent})

blog/templates/base.html
{% load blog_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="gb2312">

    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css" />
</head>


<body>
    <div id="page" class="site">
         <header class="site-header">
              <hgroup>
                  <h1>Test</h1>
                  <h2>It's a css test!</h2>
              </hgroup>
         {% include 'nav.html' %}
         </header>


    <div id="main" class="wrapper">
    {% block content %}
        {% endblock %}
    </div>


    </div>


</body>



<!--<footer>-->
        <!--<script type="text/javascript" src="{% static 'blog/js/jquery-3.1.1.js' %}"></script>-->
        <!--<script type="text/javascript" src="{% static 'blog/js/nprogress.js' %}"></script>-->
        <!--<script src="{% static 'blog/js/blog.js' %}" type="application/javascript"></script>-->
        <!--<script src="{% static 'blog/js/navigation.js' %}" type="application/javascript"></script>-->
    <!--{% block footer %}-->
    <!--{% endblock %}-->
<!--</footer>-->
</html>

blog/templates/nav.html
molly

blog/templates/pagination.html
<div class="pagination">
<span class="step-links">
{% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Previous</a>
{% endif %}
    <span class="current">
Page {{ page.number }} of {{ page.paginator.num_pages }}.
</span>
    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
</span>
</div>

blog/templates/post/detail.html
{% extends "base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}

    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url "blog:post_share" post.id %}">
            Share this post
        </a>
    </p>

    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments | pluralize }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment{{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>
            There are no comments yet.
        </p>
    {% endfor %}
    {% if new_comment %}
        <h2>Your comment has been added</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p>
                <input type="submit" value="Add comment">
            </p>
        </form>
    {% endif %}


{% endblock %}

blog/templates/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>

        </li>
    {% endfor %}
</ul>

blog/templates/post/list.html
{% extends "base.html" %}
{% load blog_tags %}



{% block title %}Stan Blog{% endblock %}

{% block content %}
    <div id="primary" class="site-content">
        <div id="content">
            <div>
                <ul>
                    {% for post in posts %}
                            <!--<div class="arc-right">-->
                                {% if tag %}
                                    <h2>Posts tagged with "{{ tag.name }}"</h2>
                                {% endif %}
                                {#                        <p class="tags">#}
                                {#                            Tags:#}
                                {#                            {% for tag in post.tags.all %}#}
                                {#                                <a href="{% url "blog:post_list_by_tag" tag.slug %}">#}
                                {#                                    {{ tag.name }}#}
                                {#                                </a>#}
                                {#                                {% if not forloop.last %}, {% endif %}#}
                                {#                            {% endfor %}#}
                                {#                        </p>#}
                                {#                            <h4 class="blue-text">#}
                                {#                                <a href="{% url "blog:detail" pk=article.id %}"#}
                                {#                                                     title="{{ article.title }}">#}
                                {#                                    {{ article.title }}#}
                                {#                                </a>#}
                                {#                            </h4>#}
                                <h4 class="entry-header">
                                    <a href="{{ post.get_absolute_url }}" title="{{ post.title }}">
                                        <h1 class="entry-header">{{ post.title }}</h1>
                                    </a>
                                    {#                            <p class="tags">Tags: {{ post.tags.all|join:", " }}</p>#}

                                </h4>
                                <p class="date article">
                                    Published {{ post.publish }} by {{ post.author }}
                                </p>
                            <p class="entry-content">
                                <span>{{ post.body }}</span>
                            </p>
                            <!--</div>-->
                    {% endfor %}
                </ul>
            <!--</div>-->
            </div>
        <!--</div>-->
                    {% include "pagination.html" with page=posts %}
            </div>
    </div>
    <!--</div>-->
    <div class="jzend"></div>

    <footer>
        <div class="footer">
            test
        </div>
    </footer>
{% endblock %}

blog/templates/post/search.html
{% extends "base.html" %}

{% block title %}Search{% endblock %}

{% block content %}
    {% if "query" in request.GET %}
        <h1>Posts containing "{{ cd.query }}</h1>
        <h3>Found {{ total_results }} results {{ total_results|pluralize }}</h3>
        {% for result in results %}
            {% with post=result.object %}
                <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a> </h4>
                {{ post.body|truncatewords:5 }}
            {% endwith %}
        {% empty %}
        <p>There are no results for you query</p>
        {% endfor %}
        <p><a href="{% url "blog:post_search" %}">Search again</a> </p>
    {% else %}
        <h1>Search for posts</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock %}

blog/templates/post/share.html
{% extends 'base.html' %}

{% block title %} Share a post {% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ cd.to }}
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by email</h1>
        <form action="."  method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send email">
        </form>
    {% endif %}
{% endblock %}